# Generated by Django 5.1.7 on 2025-03-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Driver',
        ),
    ]
